name: Mochalka
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  atk:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      uses: actions/checkout@v3
    - name: Install web driver
      run: pip install undetected-chromedriver
