name: Mochalka
on:
  workflow_dispatch:
    inputs:
      account:
        required: true
  push:

jobs:
  atk:
    runs-on: windows-latest
    steps:
    - name: Copy
      uses: actions/checkout@v3
    - name: Install web driver
      run: pip install undetected-chromedriver
    - name: Install Chrome
      shell: pwsh
      run: |
        $Path = $env:TEMP;
        $Installer = “chrome_installer.exe”;
        Invoke-WebRequest “http://dl.google.com/chrome/chrome_installer.exe" -OutFile $Path\$Installer;
        Start-Process -FilePath $Path\$Installer -Args “/silent /install” -Verb RunAs -Wait;
        Remove-Item $Path\$Installer
    - name: Script
      run: python script.py ${{inputs.account}}
    
