name: Mochalka
on:
  workflow_dispatch:

jobs:
  atk:
    runs-on: windows-latest
    steps:
    - name: Copy
      uses: actions/checkout@v3
    - name: Install web driver
      run: pip install undetected-chromedriver
    - name: Install Chrome
      run: winget install Google.Chrome
    
